version: '3'

services:
  php:
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    expose:
      - "9000"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  sqlsrv:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "DocUnix*23"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - php
      - mongodb
      - sqlsrv
