version: '3'
services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"  # Adapté en fonction du port utilisé par PHP-FPM

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  sqlsrv:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: DocUnix*23
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
