ajouter_vehicule:
    path: /ajouter-vehicule
    controller: App\Controller\VehicleController::ajouterVehicule
chercher_vehicule:
    path: /rechercher-vehicule
    controller: App\Controller\VehicleController::rechercherVehicule

