ajouter_vehicule:
    path: /ajouter-vehicule
    controller: App\Controller\VehicleController::ajouterVehicule
rechercher_vehicule:
    path: /rechercher-vehicule
    controller: App\Controller\VehicleController::rechercherVehicule
modifier_vehicule:
    path: /modifier-vehicule/{licencePlate}
    controller: App\Controller\VehicleController::modifierVehicule
supprimer_vehicule:
    path: /supprimer-vehicule/{licencePlate}
    controller: App\Controller\VehicleController::supprimerVehicule

