index:
    path: /
    controller: App\Controller\IndexController::indexPage
ajouter_vehicule:
    path: /ajouter-vehicule
    controller: App\Controller\VehicleController::ajouterVehicule
rechercher_vehicule:
    path: /rechercher-vehicule
    controller: App\Controller\VehicleController::rechercherVehicule
modifier_vehicule:
    path: /modifier-vehicule/{licencePlate}
    controller: App\Controller\VehicleController::modifierVehicule
supprimer_vehicule:
    path: /supprimer-vehicule/{licencePlate}
    controller: App\Controller\VehicleController::supprimerVehicule
afficher_contrat:
    path: /afficher-contrat
    controller: App\Controller\ContractController::index
ajouter_contrat:
    path: /ajouter-contrat
    controller: App\Controller\ContractController::new
modifier_contrat:
    path: /modifier-contrat/{id}
    controller: App\Controller\ContractController::edit
supprimer_contrat:
    path: /supprimer-contrat/{id}
    controller: App\Controller\ContractController::delete